version: '3.3'

services:

  # Wordpress Image
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: somewordpresspassword
      WORDPRESS_DB_NAME: somewordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/wp_awards

  # Command Line Interface Image
  cli:
    image: wordpress:cli
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/wp_awards

  # Wordpress PHPUnit
  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    volumes:
      - .:/app
      - testsuite:/tmp

  # Composer
  composer:
    image: composer
    volumes:
      - .:/app

  # Database Image
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: somewordpresspassword
      MYSQL_DATABASE: somewordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: somewordpresspassword

volumes:
  wordpress:
  testsuite:
  db_data: