version: '3.3'

services:

  # Wordpress Image
  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: somewordpresspassword
      WORDPRESS_DB_NAME: somewordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/user_awards

  # Command Line Interface Image
  cli:
    image: wordpress:cli
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/user_awards
      - ./backups/wp:/backups/wp

  # Wordpress PHPUnit
  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    volumes:
      - .:/app
      - testsuite:/tmp

  # Composer
  composer:
    image: composer
    volumes:
      - .:/app

  # Database Image
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: somewordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: somewordpresspassword

  # Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080

volumes:
  wordpress:
  testsuite:
  db_data: